services:
  - type: web
    name: inteebuild
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /api/health
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: INTEE_BUILDS_REPO
        sync: false
      - key: NODE_ENV
        value: production