'use strict';

const PERMISSION_SPEC = {
  notifications: { title:'Notificaciones', manifest:['android.permission.POST_NOTIFICATIONS'], runtime:true, minSdk:33, deps:['@capacitor/push-notifications','@capacitor/local-notifications'], api:'notifications', handler:'LocalNotifications', impl:{native:'LocalNotifications.schedule+requestPermissions', bridge:'Intee.notifications.schedule', webview:'Notification.requestPermission', providerOk:['capacitor','native']}, specialAccess:null },
  foreground: { title:'Foreground Service', manifest:['android.permission.FOREGROUND_SERVICE','android.permission.FOREGROUND_SERVICE_DATA_SYNC','android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK'], runtime:false, minSdk:28, deps:[], api:'foreground', handler:'RadioService', impl:{native:'RadioService.startForeground + WakeLock + MediaSession', bridge:'n/a (sistema)', webview:'n/a', providerOk:['capacitor','native','gecko']}, specialAccess:'Requiere justificación para Google Play si no es audio/media' },
  cameraMic: { title:'Cámara', manifest:['android.permission.CAMERA'], runtime:true, minSdk:23, deps:['@capacitor/camera'], api:'camera', handler:'Camera', impl:{native:'NativePermissions.request(CAMERA)+Capacitor Camera.getPhoto', bridge:'Intee.camera', webview:'getUserMedia video (WebChromeClient grant)', providerOk:['capacitor','native']}, specialAccess:null },
  microphone: { title:'Micrófono', manifest:['android.permission.RECORD_AUDIO','android.permission.MODIFY_AUDIO_SETTINGS'], runtime:true, minSdk:23, deps:['@capacitor/haptics'], api:'microphone', handler:'Microphone', impl:{native:'NativePermissions.request(RECORD_AUDIO)', bridge:'getUserMedia audio', webview:'getUserMedia audio (grant selectivo)', providerOk:['capacitor','native']}, specialAccess:null },
  storage: { title:'Almacenamiento multimedia', manifest:['android.permission.READ_MEDIA_IMAGES','android.permission.READ_MEDIA_VIDEO','android.permission.READ_MEDIA_AUDIO'], runtime:true, minSdk:33, deps:['@capacitor/filesystem'], api:'filesystem', handler:'Filesystem', impl:{native:'Filesystem.read/write + FileProvider', bridge:'Intee.files', webview:'input file + DownloadManager', providerOk:['capacitor','native']}, specialAccess:null, legacyNote:'READ_EXTERNAL_STORAGE solo para API<33, se omite si targetSdk>=33' },
  gps: { title:'Ubicación precisa', manifest:['android.permission.ACCESS_FINE_LOCATION','android.permission.ACCESS_COARSE_LOCATION'], runtime:true, minSdk:23, deps:['@capacitor/geolocation'], api:'geolocation', handler:'Geolocation', impl:{native:'NativePermissions.request(FINE/COARSE)+Geolocation.getCurrentPosition', bridge:'Intee.location', webview:'geolocation API (grant solo si gps)', providerOk:['capacitor','native']}, specialAccess:null },
  gpsBackground: { title:'Ubicación en segundo plano', manifest:['android.permission.ACCESS_BACKGROUND_LOCATION'], runtime:true, minSdk:29, deps:['@capacitor/geolocation'], api:'geolocation-bg', handler:'GeolocationBg', impl:{native:'request BACKGROUND tras FINE concedido', bridge:'watchLocation', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store: requiere justificación + aprobación, solicitar solo si la app lo necesita' },
  bluetoothScan: { title:'Bluetooth · Escanear', manifest:['android.permission.BLUETOOTH_SCAN'], runtime:true, minSdk:31, deps:['@capacitor-community/bluetooth-le'], api:'bluetooth', handler:'BluetoothLe', impl:{native:'request SCAN (neverForLocation si aplica)', bridge:'Intee bluetooth (BLE)', webview:'navigator.bluetooth.requestDevice', providerOk:['capacitor','native']}, specialAccess:null },
  bluetoothConnect: { title:'Bluetooth · Conectar', manifest:['android.permission.BLUETOOTH_CONNECT'], runtime:true, minSdk:31, deps:['@capacitor-community/bluetooth-le'], api:'bluetooth', handler:'BluetoothLe', impl:{native:'request CONNECT', bridge:'BLE connect', webview:'navigator.bluetooth', providerOk:['capacitor','native']}, specialAccess:null },
  bluetoothAdvertise: { title:'Bluetooth · Anunciar', manifest:['android.permission.BLUETOOTH_ADVERTISE'], runtime:true, minSdk:31, deps:['@capacitor-community/bluetooth-le'], api:'bluetooth', handler:'BluetoothLe', impl:{native:'request ADVERTISE', bridge:'BLE advertise', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:null },
  bluetooth: { title:'Bluetooth (compat API<31)', manifest:['android.permission.BLUETOOTH','android.permission.BLUETOOTH_ADMIN'], runtime:false, minSdk:23, maxSdk:30, deps:['@capacitor-community/bluetooth-le'], api:'bluetooth', handler:'BluetoothLe', impl:{native:'permisos normales, se conceden al instalar (en API31+ usa Scan/Connect/Advertise)', bridge:'BLE', webview:'navigator.bluetooth', providerOk:['capacitor','native']}, specialAccess:null, legacyNote:'Solo para minSdk<=30, en API31+ se usan SCAN/CONNECT/ADVERTISE' },
  phone: { title:'Teléfono', manifest:['android.permission.CALL_PHONE','android.permission.READ_PHONE_STATE','android.permission.READ_CALL_LOG'], runtime:true, minSdk:23, deps:[], api:'phone', handler:'Phone', impl:{native:'request CALL_PHONE', bridge:'tel: intent', webview:'tel: → Intent nativo', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  sms: { title:'SMS', manifest:['android.permission.SEND_SMS','android.permission.READ_SMS'], runtime:true, minSdk:23, deps:[], api:'sms', handler:'Sms', impl:{native:'request SMS', bridge:'sms: intent', webview:'sms: → Intent', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  calendar: { title:'Calendario', manifest:['android.permission.READ_CALENDAR','android.permission.WRITE_CALENDAR'], runtime:true, minSdk:23, deps:[], api:'calendar', handler:'Calendar', impl:{native:'request CALENDAR', bridge:'n/a', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:null },
  contacts: { title:'Contactos', manifest:['android.permission.READ_CONTACTS','android.permission.WRITE_CONTACTS'], runtime:true, minSdk:23, deps:[], api:'contacts', handler:'Contacts', impl:{native:'request CONTACTS', bridge:'n/a', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:null },
  sensors: { title:'Sensores', manifest:['android.permission.BODY_SENSORS','android.permission.HIGH_SAMPLING_RATE_SENSORS'], runtime:true, minSdk:23, deps:[], api:'sensors', handler:'Sensors', impl:{native:'request BODY_SENSORS', bridge:'n/a', webview:'Generic Sensor API', providerOk:['capacitor','native']}, specialAccess:null },
  nfc: { title:'NFC', manifest:['android.permission.NFC'], runtime:false, minSdk:19, deps:['phonegap-nfc'], api:'nfc', handler:'NFC', impl:{native:'NfcAdapter', bridge:'NDEFReader', webview:'NDEFReader (Chrome)', providerOk:['capacitor','native']}, specialAccess:null },
  systemAlert: { title:'Superposición', manifest:['android.permission.SYSTEM_ALERT_WINDOW'], runtime:false, minSdk:23, deps:[], api:'systemAlert', handler:'SystemAlert', impl:{native:'Settings.canDrawOverlays intent', bridge:'n/a', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Acceso especial: Settings.ACTION_MANAGE_OVERLAY_PERMISSION' },
  installPackages: { title:'Instalador', manifest:['android.permission.REQUEST_INSTALL_PACKAGES'], runtime:false, minSdk:26, deps:[], api:'installPackages', handler:'Install', impl:{native:'canRequestPackageInstalls', bridge:'n/a', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  alarmSchedule: { title:'Alarmas exactas (SCHEDULE)', manifest:['android.permission.SCHEDULE_EXACT_ALARM'], runtime:false, minSdk:31, deps:[], api:'alarm', handler:'AlarmSchedule', impl:{native:'AlarmManager.canScheduleExactAlarms', bridge:'LocalNotifications schedule', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Acceso especial revocable por usuario (recomendado)' },
  alarmUse: { title:'Alarmas exactas (USE, casos limitados)', manifest:['android.permission.USE_EXACT_ALARM'], runtime:false, minSdk:31, deps:[], api:'alarm', handler:'AlarmUse', impl:{native:'USE_EXACT_ALARM (reloj/calendario)', bridge:'LocalNotifications', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Solo reloj/alarma/calendario, Play lo verifica' },
  alarm: { title:'Alarmas (legacy selector)', manifest:['android.permission.SCHEDULE_EXACT_ALARM'], runtime:false, minSdk:31, deps:[], api:'alarm', handler:'AlarmSchedule', impl:{native:'SCHEDULE por defecto', bridge:'LocalNotifications', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Usa alarmSchedule, alarmUse solo si aplica' },
  nearby: { title:'WiFi Cercano', manifest:['android.permission.NEARBY_WIFI_DEVICES'], runtime:true, minSdk:33, deps:[], api:'nearby', handler:'Nearby', impl:{native:'request NEARBY_WIFI', bridge:'n/a', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:null },
  vibration: { title:'Vibración', manifest:['android.permission.VIBRATE'], runtime:false, minSdk:1, deps:['@capacitor/haptics'], api:'vibration', handler:'Haptics', impl:{native:'Vibrator', bridge:'Intee.vibrate', webview:'navigator.vibrate', providerOk:['capacitor','native']}, specialAccess:null },
  wakeLock: { title:'Wake Lock', manifest:['android.permission.WAKE_LOCK'], runtime:false, minSdk:1, deps:['@capacitor/device'], api:'wakelock', handler:'WakeLock', impl:{native:'PowerManager WakeLock', bridge:'screen.keepOn', webview:'WakeLock API', providerOk:['capacitor','native']}, specialAccess:null },
  biometric: { title:'Biometría', manifest:['android.permission.USE_BIOMETRIC'], runtime:false, minSdk:28, deps:[], api:'biometric', handler:'Biometric', impl:{native:'BiometricPrompt (100% nativo)', bridge:'Intee.biometric', webview:'WebAuthn', providerOk:['capacitor','native','flutter']}, specialAccess:null },
  fingerprint: { title:'Huella Digital (legacy)', manifest:['android.permission.USE_FINGERPRINT'], runtime:false, minSdk:23, maxSdk:27, deps:[], api:'biometric', handler:'Biometric', impl:{native:'FingerprintManagerCompat (100% nativo)', bridge:'Intee.biometric', webview:'WebAuthn', providerOk:['capacitor','native']}, specialAccess:null, legacyNote:'Sustituido por USE_BIOMETRIC en API28+' },
  activityRecognition: { title:'Actividad', manifest:['android.permission.ACTIVITY_RECOGNITION'], runtime:true, minSdk:29, deps:[], api:'activityRecognition', handler:'Activity', impl:{native:'ActivityRecognitionClient (100% nativo)', bridge:'Intee.activity', webview:'n/a', providerOk:['capacitor','native','flutter']}, specialAccess:null },
  ads: { title:'Publicidad Nativa', manifest:['android.permission.INTERNET','android.permission.ACCESS_NETWORK_STATE'], runtime:false, minSdk:21, deps:[], api:'ads', handler:'AdMob', impl:{native:'MobileAds.initialize + AdView/Interstitial (100% nativo)', bridge:'Intee.ads', webview:'adsense/iframe', providerOk:['capacitor','native','flutter']}, specialAccess:'Requiere AdMob App ID y compliance con GDPR' },
  // Más permisos nativos Android
  cameraFlash: { title:'Flash de Cámara', manifest:['android.permission.CAMERA'], runtime:true, minSdk:23, deps:[], api:'camera', handler:'Camera', impl:{native:'CameraManager.open + torch mode (100% nativo)', bridge:'Intee.cameraFlash', webview:'imageCapture.getPhotoSettings', providerOk:['capacitor','native']}, specialAccess:null },
  cameraAutoFocus: { title:'Auto-enfoque Cámara', manifest:['android.permission.CAMERA'], runtime:true, minSdk:23, deps:[], api:'camera', handler:'Camera', impl:{native:'Camera.Parameters.setFocusMode (100% nativo)', bridge:'Intee.cameraFocus', webview:'imageCapture.getPhotoSettings', providerOk:['capacitor','native']}, specialAccess:null },
  audioRecord: { title:'Grabación Audio', manifest:['android.permission.RECORD_AUDIO'], runtime:true, minSdk:23, deps:[], api:'audio', handler:'AudioRecord', impl:{native:'AudioRecord + MediaRecorder (100% nativo)', bridge:'Intee.audioRecord', webview:'MediaRecorder API', providerOk:['capacitor','native']}, specialAccess:null },
  videoCapture: { title:'Captura Video', manifest:['android.permission.CAMERA','android.permission.RECORD_AUDIO'], runtime:true, minSdk:23, deps:[], api:'video', handler:'VideoCapture', impl:{native:'MediaRecorder + Camera (100% nativo)', bridge:'Intee.videoCapture', webview:'MediaRecorder API', providerOk:['capacitor','native']}, specialAccess:null },
  readContacts: { title:'Leer Contactos', manifest:['android.permission.READ_CONTACTS'], runtime:true, minSdk:23, deps:[], api:'contacts', handler:'Contacts', impl:{native:'ContactsContract (100% nativo)', bridge:'Intee.readContacts', webview:'Contacts API', providerOk:['capacitor','native']}, specialAccess:null },
  writeContacts: { title:'Escribir Contactos', manifest:['android.permission.WRITE_CONTACTS'], runtime:true, minSdk:23, deps:[], api:'contacts', handler:'Contacts', impl:{native:'ContentResolver.insert (100% nativo)', bridge:'Intee.writeContacts', webview:'Contacts API', providerOk:['capacitor','native']}, specialAccess:null },
  readCalendar: { title:'Leer Calendario', manifest:['android.permission.READ_CALENDAR'], runtime:true, minSdk:23, deps:[], api:'calendar', handler:'Calendar', impl:{native:'CalendarContract (100% nativo)', bridge:'Intee.readCalendar', webview:'Calendar API', providerOk:['capacitor','native']}, specialAccess:null },
  writeCalendar: { title:'Escribir Calendario', manifest:['android.permission.WRITE_CALENDAR'], runtime:true, minSdk:23, deps:[], api:'calendar', handler:'Calendar', impl:{native:'ContentResolver.insert (100% nativo)', bridge:'Intee.writeCalendar', webview:'Calendar API', providerOk:['capacitor','native']}, specialAccess:null },
  readCallLog: { title:'Leer Log de Llamadas', manifest:['android.permission.READ_CALL_LOG'], runtime:true, minSdk:23, deps:[], api:'calllog', handler:'CallLog', impl:{native:'CallLog.Calls (100% nativo)', bridge:'Intee.readCallLog', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  processOutgoingCalls: { title:'Procesar Llamadas Salientes', manifest:['android.permission.PROCESS_OUTGOING_CALLS'], runtime:true, minSdk:29, deps:[], api:'phone', handler:'Phone', impl:{native:'CallRedirectionService (100% nativo)', bridge:'Intee.redirectCall', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  sendSms: { title:'Enviar SMS', manifest:['android.permission.SEND_SMS'], runtime:true, minSdk:23, deps:[], api:'sms', handler:'Sms', impl:{native:'SmsManager.sendTextMessage (100% nativo)', bridge:'Intee.sendSms', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  readSms: { title:'Leer SMS', manifest:['android.permission.READ_SMS'], runtime:true, minSdk:23, deps:[], api:'sms', handler:'Sms', impl:{native:'ContentResolver (100% nativo)', bridge:'Intee.readSms', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  receiveSms: { title:'Recibir SMS', manifest:['android.permission.RECEIVE_SMS'], runtime:false, minSdk:23, deps:[], api:'sms', handler:'Sms', impl:{native:'BroadcastReceiver (100% nativo)', bridge:'Intee.receiveSms', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  receiveMms: { title:'Recibir MMS', manifest:['android.permission.RECEIVE_MMS'], runtime:false, minSdk:23, deps:[], api:'sms', handler:'Sms', impl:{native:'BroadcastReceiver (100% nativo)', bridge:'Intee.receiveMms', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  readPhoneState: { title:'Leer Estado Teléfono', manifest:['android.permission.READ_PHONE_STATE'], runtime:true, minSdk:23, deps:[], api:'phone', handler:'Phone', impl:{native:'TelephonyManager (100% nativo)', bridge:'Intee.readPhoneState', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  readPhoneNumber: { title:'Leer Número Teléfono', manifest:['android.permission.READ_PHONE_NUMBERS'], runtime:true, minSdk:26, deps:[], api:'phone', handler:'Phone', impl:{native:'TelephonyManager (100% nativo)', bridge:'Intee.readPhoneNumber', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  callPhone: { title:'Llamar por Teléfono', manifest:['android.permission.CALL_PHONE'], runtime:true, minSdk:23, deps:[], api:'phone', handler:'Phone', impl:{native:'Intent.ACTION_CALL (100% nativo)', bridge:'Intee.callPhone', webview:'tel: → Intent', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  answerPhone: { title:'Contestar Llamadas', manifest:['android.permission.ANSWER_PHONE_CALLS'], runtime:true, minSdk:26, deps:[], api:'phone', handler:'Phone', impl:{native:'TelecomManager (100% nativo)', bridge:'Intee.answerPhone', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  bodySensors: { title:'Sensores Corporales', manifest:['android.permission.BODY_SENSORS'], runtime:true, minSdk:23, deps:[], api:'sensors', handler:'Sensors', impl:{native:'SensorManager (100% nativo)', bridge:'Intee.bodySensors', webview:'Generic Sensor API', providerOk:['capacitor','native']}, specialAccess:null },
  highSamplingRateSensors: { title:'Sensores Alta Tasa', manifest:['android.permission.HIGH_SAMPLING_RATE_SENSORS'], runtime:false, minSdk:31, deps:[], api:'sensors', handler:'Sensors', impl:{native:'SensorManager (permiso normal, se concede al instalar)', bridge:'Intee.highRateSensors', webview:'Generic Sensor API', providerOk:['capacitor','native']}, specialAccess:null },
  accessBackgroundLocation: { title:'Ubicación Segundo Plano', manifest:['android.permission.ACCESS_BACKGROUND_LOCATION'], runtime:true, minSdk:29, deps:[], api:'location', handler:'Location', impl:{native:'FusedLocationProvider (100% nativo)', bridge:'Intee.backgroundLocation', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store: requiere justificación' },
  useExactAlarm: { title:'Alarmas Exactas', manifest:['android.permission.USE_EXACT_ALARM'], runtime:false, minSdk:31, deps:[], api:'alarm', handler:'Alarm', impl:{native:'AlarmManager (100% nativo)', bridge:'Intee.exactAlarm', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Solo reloj/alarma/calendario' },
  scheduleExactAlarm: { title:'Programar Alarmas', manifest:['android.permission.SCHEDULE_EXACT_ALARM'], runtime:false, minSdk:31, deps:[], api:'alarm', handler:'Alarm', impl:{native:'AlarmManager.canScheduleExactAlarms (100% nativo)', bridge:'Intee.scheduleAlarm', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Acceso especial revocable' },
  requestInstallPackages: { title:'Instalar APKs', manifest:['android.permission.REQUEST_INSTALL_PACKAGES'], runtime:false, minSdk:26, deps:[], api:'install', handler:'Install', impl:{native:'PackageInstaller (100% nativo)', bridge:'Intee.installApk', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  systemAlertWindow: { title:'Ventana Flotante', manifest:['android.permission.SYSTEM_ALERT_WINDOW'], runtime:false, minSdk:23, deps:[], api:'systemAlert', handler:'SystemAlert', impl:{native:'WindowManager.LayoutParams (100% nativo)', bridge:'Intee.systemAlert', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Acceso especial' },
  manageExternalStorage: { title:'Gestión Almacenamiento', manifest:['android.permission.MANAGE_EXTERNAL_STORAGE'], runtime:true, minSdk:30, deps:[], api:'storage', handler:'Storage', impl:{native:'StorageManager (100% nativo)', bridge:'Intee.manageStorage', webview:'FileSystem API', providerOk:['capacitor','native']}, specialAccess:'Solo para API30+' },
  readExternalStorage: { title:'Leer Almacenamiento', manifest:['android.permission.READ_EXTERNAL_STORAGE'], runtime:true, minSdk:16, deps:[], api:'storage', handler:'Storage', impl:{native:'Environment.getExternalStorageDirectory (100% nativo)', bridge:'Intee.readStorage', webview:'FileSystem API', providerOk:['capacitor','native']}, specialAccess:'Legacy para API<33' },
  writeExternalStorage: { title:'Escribir Almacenamiento', manifest:['android.permission.WRITE_EXTERNAL_STORAGE'], runtime:true, minSdk:16, deps:[], api:'storage', handler:'Storage', impl:{native:'FileOutputStream (100% nativo)', bridge:'Intee.writeStorage', webview:'FileSystem API', providerOk:['capacitor','native']}, specialAccess:'Legacy para API<33' },
  getAccounts: { title:'Obtener Cuentas', manifest:['android.permission.GET_ACCOUNTS'], runtime:true, minSdk:23, deps:[], api:'accounts', handler:'Accounts', impl:{native:'AccountManager (100% nativo)', bridge:'Intee.getAccounts', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  readCallLog: { title:'Leer Log Llamadas', manifest:['android.permission.READ_CALL_LOG'], runtime:true, minSdk:23, deps:[], api:'calls', handler:'Calls', impl:{native:'CallLog.Calls (100% nativo)', bridge:'Intee.readCallLog', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Play Store restringido' },
  nearbyWifiDevices: { title:'WiFi Cercano', manifest:['android.permission.NEARBY_WIFI_DEVICES'], runtime:true, minSdk:33, deps:[], api:'wifi', handler:'Wifi', impl:{native:'WifiManager (100% nativo)', bridge:'Intee.nearbyWifi', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:null },
  changeWifiState: { title:'Cambiar Estado WiFi', manifest:['android.permission.CHANGE_WIFI_STATE'], runtime:false, minSdk:23, deps:[], api:'wifi', handler:'Wifi', impl:{native:'WifiManager (permiso normal, se concede al instalar)', bridge:'Intee.changeWifi', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:null },
  changeNetworkState: { title:'Cambiar Estado Red', manifest:['android.permission.CHANGE_NETWORK_STATE'], runtime:false, minSdk:23, deps:[], api:'network', handler:'Network', impl:{native:'ConnectivityManager (permiso normal, se concede al instalar)', bridge:'Intee.changeNetwork', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:null },
  bluetoothPrivileged: { title:'Bluetooth Privilegiado', manifest:['android.permission.BLUETOOTH_PRIVILEGED'], runtime:false, minSdk:30, deps:[], api:'bluetooth', handler:'Bluetooth', impl:{native:'BluetoothAdapter (100% nativo)', bridge:'Intee.bluetoothPrivileged', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Solo apps del sistema' },
  bluetoothConnect: { title:'Bluetooth Conectar', manifest:['android.permission.BLUETOOTH_CONNECT'], runtime:true, minSdk:31, deps:[], api:'bluetooth', handler:'Bluetooth', impl:{native:'BluetoothDevice (100% nativo)', bridge:'Intee.bluetoothConnect', webview:'navigator.bluetooth', providerOk:['capacitor','native']}, specialAccess:null },
  bluetoothScan: { title:'Bluetooth Escanear', manifest:['android.permission.BLUETOOTH_SCAN'], runtime:true, minSdk:31, deps:[], api:'bluetooth', handler:'Bluetooth', impl:{native:'BluetoothLeScanner (100% nativo)', bridge:'Intee.bluetoothScan', webview:'navigator.bluetooth', providerOk:['capacitor','native']}, specialAccess:null },
  nfc: { title:'NFC', manifest:['android.permission.NFC'], runtime:false, minSdk:19, deps:[], api:'nfc', handler:'NFC', impl:{native:'NfcAdapter (100% nativo)', bridge:'Intee.nfc', webview:'NDEFReader', providerOk:['capacitor','native']}, specialAccess:null },
  infrared: { title:'Infrarrojos', manifest:['android.permission.TRANSMIT_IR'], runtime:false, minSdk:19, deps:[], api:'infrared', handler:'Infrared', impl:{native:'ConsumerIrManager (100% nativo)', bridge:'Intee.infrared', webview:'n/a', providerOk:['capacitor','native']}, specialAccess:'Solo dispositivos con IR' },
  accessCoarseLocation: { title:'Ubicación Aproximada', manifest:['android.permission.ACCESS_COARSE_LOCATION'], runtime:true, minSdk:23, deps:[], api:'location', handler:'Location', impl:{native:'LocationManager (100% nativo)', bridge:'Intee.coarseLocation', webview:'geolocation API', providerOk:['capacitor','native']}, specialAccess:null },
  accessFineLocation: { title:'Ubicación Precisa', manifest:['android.permission.ACCESS_FINE_LOCATION'], runtime:true, minSdk:23, deps:[], api:'location', handler:'Location', impl:{native:'FusedLocationProvider (100% nativo)', bridge:'Intee.fineLocation', webview:'geolocation API', providerOk:['capacitor','native']}, specialAccess:null },
  vibrate: { title:'Vibración', manifest:['android.permission.VIBRATE'], runtime:false, minSdk:1, deps:[], api:'vibration', handler:'Vibration', impl:{native:'Vibrator (100% nativo)', bridge:'Intee.vibrate', webview:'navigator.vibrate', providerOk:['capacitor','native']}, specialAccess:null },
  wakeLock: { title:'Wake Lock', manifest:['android.permission.WAKE_LOCK'], runtime:false, minSdk:1, deps:[], api:'wakelock', handler:'WakeLock', impl:{native:'PowerManager.WakeLock (100% nativo)', bridge:'Intee.wakeLock', webview:'WakeLock API', providerOk:['capacitor','native']}, specialAccess:null },
  foregroundService: { title:'Servicio Foreground', manifest:['android.permission.FOREGROUND_SERVICE','android.permission.FOREGROUND_SERVICE_DATA_SYNC','android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK'], runtime:false, minSdk:28, deps:[], api:'foreground', handler:'Foreground', impl:{native:'Service.startForeground (100% nativo)', bridge:'n/a (sistema)', webview:'n/a', providerOk:['capacitor','native','gecko']}, specialAccess:'Requiere justificación para Google Play' },
  notifications: { title:'Notificaciones', manifest:['android.permission.POST_NOTIFICATIONS'], runtime:true, minSdk:33, deps:[], api:'notifications', handler:'Notifications', impl:{native:'NotificationManager (100% nativo)', bridge:'Intee.notifications', webview:'Notification API', providerOk:['capacitor','native']}, specialAccess:null },
  internet: { title:'Internet', manifest:['android.permission.INTERNET','android.permission.ACCESS_NETWORK_STATE','android.permission.ACCESS_WIFI_STATE'], runtime:false, minSdk:1, deps:[], api:'network', handler:'Network', impl:{native:'ConnectivityManager (100% nativo)', bridge:'n/a (sistema)', webview:'fetch API', providerOk:['capacitor','native','flutter','tauri']}, specialAccess:null },
  storage: { title:'Almacenamiento Multimedia', manifest:['android.permission.READ_MEDIA_IMAGES','android.permission.READ_MEDIA_VIDEO','android.permission.READ_MEDIA_AUDIO'], runtime:true, minSdk:33, deps:[], api:'storage', handler:'Storage', impl:{native:'MediaStore (100% nativo)', bridge:'Intee.storage', webview:'FileSystem API', providerOk:['capacitor','native']}, specialAccess:null, legacyNote:'READ_EXTERNAL_STORAGE solo para API<33' }
};


const BG_LOCATION = 'android.permission.ACCESS_BACKGROUND_LOCATION';
const MANAGE_STORAGE = 'android.permission.MANAGE_EXTERNAL_STORAGE';

// Lote runtime generado EXACTAMENTE desde los permisos seleccionados:
// todo permiso con runtime:true entra al batch, excepto background (two-step)
// y manage-storage (va por Settings). Nada hardcodeado que se desfase.

function runtimeBatchConsts(cfg) {
  const out = [];
  Object.entries(cfg.permissions || {}).forEach(([k, v]) => {
    if (!v) return;
    const spec = PERMISSION_SPEC[k];
    if (!spec || !spec.runtime) return;
    spec.manifest.forEach(m => {
      if (m === BG_LOCATION || m === MANAGE_STORAGE) return;
      out.push('Manifest.permission.' + m.split('.').pop());
    });
  });
  return [...new Set(out)];
}


function wantsBackground(cfg) {
  const p = cfg.permissions || {};
  return !!(p.gpsBackground || p.accessBackgroundLocation);
}


function specialNeeds(cfg) {
  const p = cfg.permissions || {};
  return {
    overlay: !!(p.systemAlert || p.systemAlertWindow),
    install: !!(p.installPackages || p.requestInstallPackages),
    alarm: !!(p.alarmSchedule || p.alarm || p.scheduleExactAlarm),
    manage: !!p.manageExternalStorage
  };
}


function needsSpecialFile(cfg) {
  const n = specialNeeds(cfg);
  return n.overlay || n.install || n.alarm || n.manage;
}


module.exports = {
  PERMISSION_SPEC,
  BG_LOCATION,
  MANAGE_STORAGE,
  runtimeBatchConsts,
  wantsBackground,
  specialNeeds,
  needsSpecialFile
};
